version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: myhost
    ports:
      - 5001:5000
    volumes:
      - ~/.gitconfig:/home/devops/.gitconfig
      - ~/.ssh/:/home/devops/.ssh/
      - ..:/workspace
    command: sleep infinity
    environment:
      DATABASE_URI: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres1:5432/${POSTGRES_DB}"
      FASK_APP: services:app
    networks:
      - dev
    depends_on:
      - postgres1

  postgres1:
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres_data:

networks:
  dev:
